config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  #  match 'admin/handbags', :to => 'admin/handbags#clean', :via => [:get]

end
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :handbags do
      member do
        put :clean_completed, :repair_completed, :colour_completed, :move_limbo, :quality_completed
      end
      collection do
        post :update_positions
        get :clean, :repair, :colour, :limbo, :complete, :quality, :archive, :overdue, :complaints
      end

    end
    resources :microposts, only: [:create, :destroy]
  end
end

app/models/spree/handbag.rb
module Spree
  class Handbag < ActiveRecord::Base
    belongs_to :user
    has_many :microposts , class_name: Spree::Micropost, dependent: :destroy
    validates :make,:colour,:arrival_date,:completion_date,:user_id,:work_details,:security_tag,:postage,:price, presence: true
    mount_uploaders :pictures, PictureUploader
    validate  :picture_size
    validate  :at_least_one_is_checked
    before_validation :init, on: :create
    validate  :date_for_stage_exists
    validate  :if_quality_controlled

    acts_as_list
    default_scope { order(:completion_date) }

    def init
      count = {'is_clean' => is_clean, 'is_repair' => is_repair, 'is_colour' => is_colour}.values.count(true)
      days_per_stage = (completion_date - arrival_date).to_i / count
      if is_clean == true
        self.clean_by_date = arrival_date + days_per_stage
      end
      if is_repair == true
        if count == 1
          self.repair_by_date = completion_date
        elsif count == 2
          self.repair_by_date = arrival_date + days_per_stage
        else
          self.repair_by_date = arrival_date + (days_per_stage * 2)
        end
      end
      if is_colour == true
        self.colour_by_date = completion_date
      end
      if is_clean == true
        self.stage = 1
      elsif is_repair == true
        self.stage = 2
      elsif is_colour == true
        self.stage = 3
      end
    end

    # Validates the size of an uploaded picture.
    def picture_size
      if pictures.size > 5.megabytes
        errors.add(:pictures, "should be less than 5MB")
      end
    end

    def self.search(search)
      where("security_tag LIKE ?", "%#{search}%")
    end

    def at_least_one_is_checked
      errors.add(:base, "Select at least one work type") unless is_clean || is_repair || is_colour
    end

    def if_quality_controlled
      if is_quality_controlled == true && !user.opted_out?
        user.opt_out
      elsif is_quality_controlled == false && user.opted_out?
        user.opt_in
      end
    end

    def date_for_stage_exists
         if is_clean && clean_by_date == nil
          errors.add(:base, "Date needs to be generated for clean by date.")
         elsif is_repair && repair_by_date == nil
          errors.add(:base, "Date needs to be generated for repair by date.")
         elsif is_colour && colour_by_date == nil
          errors.add(:base, "Date needs to be generated for colour by date.")
          end
      end

    scope :is_clean, -> { where('is_clean IS true AND stage = 1').reorder(:clean_by_date) }
    scope :is_repair, -> { where('is_repair IS true AND stage = 2').reorder(:repair_by_date) }
    scope :is_colour, -> { where('is_colour IS true AND stage = 3').reorder(:colour_by_date) }
    scope :is_quality, -> { where(stage: 4) }
    scope :is_complete, -> { where(stage: 5) }
    scope :is_limbo, -> { where(stage: 6) }
    scope :is_archive, -> { where(stage: 7) }
    scope :is_overdue, -> { where(stage: 8) }
    scope :is_complaints, -> { where(stage: 9) }
  end
end

app/controllers/spree/admin/handbags_controller.rb
module Spree
  module Admin
    class HandbagsController < ResourceController

      def index
        @handbags = Spree::Handbag.all.page(params[:page]).per(50)
        if params[:search]
          @handbags = Spree::Handbag.ransack({
                                               m: 'or',
                                               user_bill_address_lastname_start: params[:search],
                                               user_bill_address_firstname_start: params[:search],
                                               user_ship_address_lastname_start: params[:search],
                                               user_ship_address_firstname_start: params[:search],
                                               user_email_start: params[:search],
                                               security_tag_start: params[:search],
                                               make_start: params[:search],
                                               agent_start: params[:search]
          }).result.limit(10).page(params[:page]).per(50)
        else
          @handbags = Spree::Handbag.all.page(params[:page]).per(50)
        end
      end

      def collection_actions
        [:index, :clean, :repair, :colour, :quality, :complete, :limbo, :archive, :overdue, :complaints]
      end

      def new
        @handbag = Handbag.new
        @readonly = false
      end

      def clean
        @handbags = Spree::Handbag.is_clean.page(params[:page]).per(50)
        if params[:search]
          @handbags = Spree::Handbag.is_clean.ransack({
                                                        m: 'or',
                                                        user_bill_address_lastname_start: params[:search],
                                                        user_bill_address_firstname_start: params[:search],
                                                        user_ship_address_lastname_start: params[:search],
                                                        user_ship_address_firstname_start: params[:search],
                                                        user_email_start: params[:search],
                                                        security_tag_start: params[:search],
                                                        make_start: params[:search],
                                                        agent_start: params[:search]
          }).result.limit(10).page(params[:page])
        else
          @handbags = Spree::Handbag.is_clean.page(params[:page]).per(50)
        end
      end

      def repair
        @handbags = Spree::Handbag.is_repair.page(params[:page]).per(50)
        if params[:search]
          @handbags = Spree::Handbag.is_repair.ransack({
                                                         m: 'or',
                                                         user_bill_address_lastname_start: params[:search],
                                                         user_bill_address_firstname_start: params[:search],
                                                         user_ship_address_lastname_start: params[:search],
                                                         user_ship_address_firstname_start: params[:search],
                                                         user_email_start: params[:search],
                                                         security_tag_start: params[:search],
                                                         make_start: params[:search],
                                                         agent_start: params[:search]
          }).result.limit(10).page(params[:page])
        else
          @handbags = Spree::Handbag.is_repair.page(params[:page]).per(50)
        end
      end
      def colour
        @handbags = Spree::Handbag.is_colour.page(params[:page]).per(50)
        if params[:search]
          @handbags = Spree::Handbag.is_colour.ransack({
                                                         m: 'or',
                                                         user_bill_address_lastname_start: params[:search],
                                                         user_bill_address_firstname_start: params[:search],
                                                         user_ship_address_lastname_start: params[:search],
                                                         user_ship_address_firstname_start: params[:search],
                                                         user_email_start: params[:search],
                                                         security_tag_start: params[:search],
                                                         make_start: params[:search],
                                                         agent_start: params[:search]
          }).result.limit(10).page(params[:page])
        else
          @handbags = Spree::Handbag.is_colour.page(params[:page]).per(50)
        end
      end

      def quality
        @handbags = Spree::Handbag.is_quality.page(params[:page]).per(50)
        if params[:search]
          @handbags = Spree::Handbag.is_quality.ransack({
                                                          m: 'or',
                                                          user_bill_address_lastname_start: params[:search],
                                                          user_bill_address_firstname_start: params[:search],
                                                          user_ship_address_lastname_start: params[:search],
                                                          user_ship_address_firstname_start: params[:search],
                                                          user_email_start: params[:search],
                                                          security_tag_start: params[:search],
                                                          make_start: params[:search],
                                                          agent_start: params[:search]
          }).result.limit(10).page(params[:page])
        else
          @handbags = Spree::Handbag.is_quality.page(params[:page]).per(50)
        end
      end

      def complete
        @handbags = Spree::Handbag.is_complete.page(params[:page]).per(50)
        if params[:search]
          @handbags = Spree::Handbag.is_complete.ransack({
                                                           m: 'or',
                                                           user_bill_address_lastname_start: params[:search],
                                                           user_bill_address_firstname_start: params[:search],
                                                           user_ship_address_lastname_start: params[:search],
                                                           user_ship_address_firstname_start: params[:search],
                                                           user_email_start: params[:search],
                                                           security_tag_start: params[:search],
                                                           make_start: params[:search],
                                                           agent_start: params[:search]
          }).result.limit(10).page(params[:page])
        else
          @handbags = Spree::Handbag.is_complete.page(params[:page]).per(50)
        end
      end
      def limbo
        @handbags = Spree::Handbag.is_limbo.page(params[:page]).per(50)
        if params[:search]
          @handbags = Spree::Handbag.is_limbo.ransack({
                                                        m: 'or',
                                                        user_bill_address_lastname_start: params[:search],
                                                        user_bill_address_firstname_start: params[:search],
                                                        user_ship_address_lastname_start: params[:search],
                                                        user_ship_address_firstname_start: params[:search],
                                                        user_email_start: params[:search],
                                                        security_tag_start: params[:search],
                                                        make_start: params[:search],
                                                        agent_start: params[:search]
          }).result.limit(10).page(params[:page])
        else
          @handbags = Spree::Handbag.is_limbo.page(params[:page]).per(50)
        end
      end
      def complaints
        @handbags = Spree::Handbag.is_complaints.page(params[:page]).per(50)
        if params[:search]
          @handbags = Spree::Handbag.is_complaints.ransack({
                                                        m: 'or',
                                                        user_bill_address_lastname_start: params[:search],
                                                        user_bill_address_firstname_start: params[:search],
                                                        user_ship_address_lastname_start: params[:search],
                                                        user_ship_address_firstname_start: params[:search],
                                                        user_email_start: params[:search],
                                                        security_tag_start: params[:search],
                                                        make_start: params[:search],
                                                        agent_start: params[:search]
          }).result.limit(10).page(params[:page])
        else
          @handbags = Spree::Handbag.is_complaints.page(params[:page]).per(50)
        end
      end
      def archive
        @handbags = Spree::Handbag.is_archive.page(params[:page]).per(50)
        if params[:search]
          @handbags = Spree::Handbag.is_archive.ransack({

app/views/spree/admin/handbags/_cleaned.js.erb
<% success = flash.discard(:success)
if success %>
  show_flash('success', "<%= j success %>")
<% end %>

app/views/spree/admin/handbags/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture %>
  </span>
<% end %>

app/views/spree/admin/handbags/_search.html.erb
<%= form_tag(request.env['PATH_INFO'], :method => "get", id: "search-form", class: 'form-inline') do %>
<%= text_field_tag :search, params[:search], placeholder: "security, name, email..", :class => 'form-control' %>
<%= submit_tag "Search", class: 'btn btn-primary' %>
<% end %>

app/views/spree/admin/handbags/colour.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:colour) %> (<%= Spree::Handbag.is_colour.count %>)
<% end %>

<% content_for :page_actions do %>
<% end %>

<%= render 'search' %>

<table class="table sortable" id="colour_handbags" data-hook data-sortable-link="<%= update_positions_admin_handbags_url %>">
  <thead>
    <tr data-hook="admin_handbags_index_headers">
      <th class="no-border"><%= t(:id, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:make, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:colour, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:security_tag, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:colour_by_date, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:flagged, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th data-hook="admin_handbags_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @handbags.each do |handbag| %>
      <tr id="<%= spree_dom_id handbag %>" data-hook="admin_handbags_index_rows" class="<%= cycle('odd', 'even')%>">
        <td><%= link_to handbag.id, object_url(handbag) %></td>
        <td><%= link_to handbag.make, object_url(handbag) %></td>
        <td><%= link_to handbag.colour, object_url(handbag) %></td>
        <td><%= link_to handbag.security_tag, object_url(handbag) %></td>

        <td><%= link_to handbag.colour_by_date.strftime("%d/%m/%Y"), object_url(handbag) %></td>
        <td<% if handbag.two_week_turnaround || handbag.returned_bag || handbag.is_quality_controlled || handbag.trade %>
        class="flagged"
        <% end %>
         ></td>
        <td data-hook="admin_handbags_index_row_actions" class="actions text-right">
          <%= link_to_with_icon('check', 'Complete', colour_completed_admin_handbag_path(handbag), :remote=> true, :method => :put,data: { confirm: "Are you sure?" }, class: 'btn btn-success btn-sm complete-resource') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @handbags %>

app/views/spree/admin/handbags/complete.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:completed_bags) %> (<%= Spree::Handbag.is_complete.count %>)
<% end %>

<% content_for :page_actions do %>
<% end %>

<%= render 'search' %>

<table class="table sortable" id="completed_handbags" data-hook data-sortable-link="<%= update_positions_admin_handbags_url %>">
  <thead>
    <tr data-hook="admin_handbags_index_headers">
      <th class="no-border"><%= t(:id, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:make, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:colour, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:security_tag, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:completion_date, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th data-hook="admin_handbags_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @handbags.each do |handbag| %>
      <tr id="<%= spree_dom_id handbag %>" data-hook="admin_handbags_index_rows" class="<%= cycle('odd', 'even')%>">
        <td><%= link_to handbag.id, object_url(handbag) %></td>
        <td><%= link_to handbag.make, object_url(handbag) %></td>
        <td><%= link_to handbag.colour, object_url(handbag) %></td>
        <td><%= link_to handbag.security_tag, object_url(handbag) %></td>
        <td><%= link_to handbag.completion_date.strftime("%d/%m/%Y"), object_url(handbag) %></td>

        <td data-hook="admin_handbags_index_row_actions" class="actions text-right">
          <%= link_to_with_icon('check', 'Archive', admin_handbag_path(handbag, :handbag => {:stage => 7}), :remote=> true, :method => :put,data: { confirm: "Are you sure?" }, class: 'btn btn-success btn-sm complete-resource') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @handbags %>

app/views/spree/admin/handbags/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_handbag) %> ID: <%= @handbag.id %>

<% end %>

<div data-hook="admin_handbag_edit_form_header">
  <%= render 'spree/shared/error_messages', target: @handbag %>
</div>

<div data-hook="admin_handbag_edit_form">
  <%= form_for [:admin, @handbag] do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'form', f: f %>
        <%= render 'spree/admin/shared/edit_resource_links' %>
      </div>
    </div>
  <% end %>
</div>

app/views/spree/admin/handbags/index.html.erb
<% content_for :page_title do %>
<%= Spree.t(:all_handbags) %> (<%= Spree::Handbag.all.count %>)
<% end %>
<% content_for :page_actions do %>
<% end %>
<%= render 'search' %>
<table class="table sortable" id="limbo_handbags" data-hook data-sortable-link="<%= update_positions_admin_handbags_url %>">
  <thead>
    <tr data-hook="admin_handbags_index_headers">
      <th class="no-border"><%= t(:id, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:make, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:colour, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:security_tag, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:completion_date, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:flagged, scope: 'activerecord.attributes.spree/handbag') %></th>
      <% if can?(:create, Spree::Handbag) %>
      <th>Edit</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @handbags.each do |handbag| %>
    <tr id="<%= spree_dom_id handbag %>" data-hook="admin_handbags_index_rows" class="<%= cycle('odd', 'even')%>">
      <td><%= link_to handbag.id, object_url(handbag) %></td>
      <td><%= link_to handbag.make, object_url(handbag) %></td>
      <td><%= link_to handbag.colour, object_url(handbag) %></td>
      <td><%= link_to handbag.security_tag, object_url(handbag) %></td>
      <td><%= link_to handbag.completion_date.strftime("%d/%m/%Y"), object_url(handbag) %></td>
      <td<% if handbag.two_week_turnaround || handbag.returned_bag || handbag.is_quality_controlled || handbag.trade %>
      class="flagged"
      <% end %>
       ></td>
      <% if can?(:create, Spree::Handbag) %>
      <td><%= link_to_edit handbag, no_text: true %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @handbags %>

app/views/spree/admin/handbags/limbo.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:limbo) %> (<%= Spree::Handbag.is_limbo.count %>)
<% end %>

<% content_for :page_actions do %>
<% end %>

<%= render 'search' %>

<table class="table sortable" id="limbo_handbags" data-hook data-sortable-link="<%= update_positions_admin_handbags_url %>">
  <thead>
    <tr data-hook="admin_handbags_index_headers">
      <th class="no-border"><%= t(:id, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:make, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:colour, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:security_tag, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:completion_date, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:flagged, scope: 'activerecord.attributes.spree/handbag') %></th>
<% if can?(:create, Spree::Handbag) %>
      <th>Edit</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @handbags.each do |handbag| %>
      <tr id="<%= spree_dom_id handbag %>" data-hook="admin_handbags_index_rows" class="<%= cycle('odd', 'even')%>">
        <td><%= link_to handbag.id, object_url(handbag) %></td>
        <td><%= link_to handbag.make, object_url(handbag) %></td>
        <td><%= link_to handbag.colour, object_url(handbag) %></td>
        <td><%= link_to handbag.security_tag, object_url(handbag) %></td>
        <td><%= link_to handbag.completion_date.strftime("%d/%m/%Y"), object_url(handbag) %></td>
        <td<% if handbag.two_week_turnaround || handbag.returned_bag || handbag.is_quality_controlled || handbag.trade %>
        class="flagged"
        <% end %>
         ></td>
        <% if can?(:create, Spree::Handbag) %>
        <td><%= link_to_edit handbag, no_text: true %></td>
              <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @handbags %>

app/views/spree/admin/handbags/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_handbag) %>
<% end %>

<div data-hook="admin_handbag_new_form_header">
  <%= render 'spree/shared/error_messages', target: @handbag %>
</div>

<div data-hook="admin_handbag_new_form">
  <%= form_for [:admin, @handbag], html: { multipart: true } do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'form', f: f %>
        <%= render 'spree/admin/shared/new_resource_links' %>
      </div>
    </div>
  <% end %>
</div>

app/views/spree/admin/handbags/overdue.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:overdue) %> (<%= Spree::Handbag.is_overdue.count %>)
<% end %>

<% content_for :page_actions do %>
<% end %>

<%= render 'search' %>

<table class="table sortable" id="overdue_handbags" data-hook data-sortable-link="<%= update_positions_admin_handbags_url %>">
  <thead>
    <tr data-hook="admin_handbags_index_headers">
      <th class="no-border"><%= t(:id, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:make, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:colour, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:security_tag, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:completion_date, scope: 'activerecord.attributes.spree/handbag') %></th>
    </tr>
  </thead>
  <tbody>
    <% @handbags.each do |handbag| %>
      <tr id="<%= spree_dom_id handbag %>" data-hook="admin_handbags_index_rows" class="<%= cycle('odd', 'even')%>">
        <td><%= link_to handbag.id, object_url(handbag) %></td>
        <td><%= link_to handbag.make, object_url(handbag) %></td>
        <td><%= link_to handbag.colour, object_url(handbag) %></td>
        <td><%= link_to handbag.security_tag, object_url(handbag) %></td>
        <td><%= link_to handbag.completion_date.strftime("%d/%m/%Y"), object_url(handbag) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @handbags %>

app/views/spree/admin/handbags/quality.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:quality_control) %> (<%= Spree::Handbag.is_quality.count %>)
<% end %>

<% content_for :page_actions do %>
<% end %>

<%= render 'search' %>

<table class="table sortable" id="quality_handbags" data-hook data-sortable-link="<%= update_positions_admin_handbags_url %>">
  <thead>
    <tr data-hook="admin_handbags_index_headers">
      <th class="no-border"><%= t(:id, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:make, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:colour, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:security_tag, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:completion_date, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th><%= t(:flagged, scope: 'activerecord.attributes.spree/handbag') %></th>
      <th data-hook="admin_handbags_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @handbags.each do |handbag| %>
      <tr id="<%= spree_dom_id handbag %>" data-hook="admin_handbags_index_rows" class="<%= cycle('odd', 'even')%>">
        <td><%= link_to handbag.id, object_url(handbag) %></td>
        <td><%= link_to handbag.make, object_url(handbag) %></td>
        <td><%= link_to handbag.colour, object_url(handbag) %></td>
        <td><%= link_to handbag.security_tag, object_url(handbag) %></td>
        <td><%= link_to handbag.completion_date.strftime("%d/%m/%Y"), object_url(handbag) %></td>
        <td<% if handbag.two_week_turnaround || handbag.returned_bag || handbag.is_quality_controlled || handbag.trade %>
        class="flagged"
        <% end %>
         ></td>
        <td data-hook="admin_handbags_index_row_actions" class="actions text-right">
          <%= link_to_with_icon('check', 'Complete', quality_completed_admin_handbag_path(handbag), :remote=> true, :method => :put,data: { confirm: "Are you sure?" }, class: 'btn btn-success btn-sm complete-resource') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @handbags %>

app/views/spree/admin/handbags/show.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:handbag) %> ID: <%= @handbag.id %>
<% end %>
<% content_for :page_actions do %>
<% if @handbag.stage != 6 %>
 <%= button_link_to Spree.t(:limbo_bag), move_limbo_admin_handbag_path(@handbag), class: 'btn-warning', icon: 'edit', id: 'admin_limbo_handbag_link', :method => :put, data: { confirm: "Have you added a reason?" } %>
 <% end %>
<% if can?(:create, Spree::Handbag) %>
<%= button_link_to Spree.t(:edit_bag), edit_admin_handbag_path(@handbag), class: 'btn-info', icon: 'edit', id: 'admin_edit_handbag_link' %>

<% end %>
 <% end if can?(:read, Spree::Handbag) %>



<div class="row">
  <div class="col-md-8">

<%= render partial: 'spree/admin/shared/handbag_summary' %>
</div>
<div class="col-md-4">
<% @handbag.pictures.each do |picture| %>
              <a href="<%=picture.url%>">
   <%= image_tag picture.url, :style => "max-width:49%" %>
   </a>
   <% end %>
</div>
</div>

     <% if @microposts.any? %>
        <h3>Posts (<%= @handbag.microposts.count %>)</h3>
<div class="row">
  <div class="col-md-8">

        <ol class="microposts">
          <% @microposts.each do |micropost| %>
             <li id="micropost-<%= micropost.id %>">
              <span class="user"><%= micropost.user.email %></span>
              <span class="content"><%= micropost.content %></span>
              <a href="<%=micropost.picture.url%>">
              <%= image_tag micropost.picture.url, :style => "max-width:100%" if micropost.picture? %>
              </a>
              <span class="timestamp">
                Added on <%= micropost.created_at.strftime("%d/%m/%Y") %>
              </span>
            </li>
          <% end %>
        </ol>
      <%= paginate @microposts %>
    <% end %>
  </div>
    <div class="col-md-4">
<%= form_for(:micropost, :url => admin_microposts_url, html: { multipart: true }) do |f| %>
  <%= render 'spree/shared/error_messages', target: @micropost %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new comment...", style: 'width:100%' %>
  </div>
   <%= f.hidden_field :handbag_id, :value => @handbag.id %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <span class="picture">
<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>
  </div>

</div>

app/views/spree/admin/handbags/update.js.erb
<% success = flash.discard(:success)
if success %>
  show_flash('success', "<%= j success %>")
<% end %>